spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/modoo-report?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/modoo-report-test
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect


